### ISSUE TITLE
Erreur innatendue sur /user/server/get

### ISSUE THREAD

**Issue by FlowArg** [Chaika9/TestServerApiWiki#1]
**Procédure**
Session de Chaika9 => Création d'un code d'invitation pour un serveur qui lui appartient
Session de FlowArg => Récupération du serverId avec le code d'invitation
Session de FlowArg => Récupère les informations du serveur avec le serverId retourné sur `/user/server/get`. Aucun problème.
Session de Chaika9 => Récupère les informations du même serveur avec le même serverId sur `/user/server/get`. Erreur :
```json
{"error":"WhiteListException","errorMessage":"Player not whitelist"}
```

Le code a été créé pour le serveur `test`.
Si je tente de récupérer avec la session de FlowArg les informations du serveur `test2`, j'ai l'erreur mentionnée ci-dessus, ce qui est logique. Il semblerait donc que l'owner ait besoin d'être ajouté à la whitelist, ce qui n'a pas trop de sens xD.

**Comment by Chaika9** [comment]
Bug corrigé ^^
